-- Generated by matugen from {{image}} — do not edit (see theme/matugen)
return {
    accent          = "rgba({{colors.primary.default.hex_stripped}}ff)",
    accent2         = "rgba({{colors.tertiary.default.hex_stripped}}ff)",
    inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}ff)",
    shadow_color    = 0xff{{colors.shadow.default.hex_stripped}},
}
