-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- Already provided by LazyVim (no need to remap):
--   <C-s> save, <leader>qq quit all, ]d/[d diagnostics,
--   <leader>sb buffer lines, <leader>sk keymaps (snacks picker),
--   <leader>xx diagnostics (Trouble), <C-/> terminal (snacks)
-- Surround (mini.surround extra): gsa add, gsd delete, gsr replace, gsh highlight, gsf/gsF find
