config_version = 14

[bar.default]
background_opacity = 0.2799999937415123
center = [ "clock", "spacer_2", "media" ]
end = [
    "group:g1",
    "caffeine",
    "cpu",
    "ram",
    "portctl",
    "updates",
    "notifications",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "power_profile",
    "battery",
    "control-center",
    "session"
]
padding = 0
thickness = 28

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border_width = 1.0
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "privacy", "tray" ]
    opacity = 1.0
    padding = 6.0

[control_center]
hidden_tabs = [ "weather" ]

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[lockscreen]
blur_intensity = 0.12
tint_intensity = 0.25

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-widget-time",
    "lockscreen-widget-date",
    "lockscreen-widget-avatar",
    "lockscreen-widget-name",
    "lockscreen-login-box@eDP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1520.0
    cy = 922.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface"
        background_opacity = 0.55000000000000004
        background_radius = 22.0
        center_password_text = false
        input_opacity = 0.84999999999999998
        input_radius = 14.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-avatar]
    box_height = 104.0
    box_width = 104.0
    cx = 1236.0
    cy = 770.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-avatar.settings]
        background = false
        image_path = "/home/ayoub/.local/share/rice/avatar-round.png"
        opacity = 1.0

    [lockscreen_widgets.widget.lockscreen-widget-date]
    box_height = 110.0
    box_width = 420.0
    cx = 270.0
    cy = 950.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-date.settings]
        background = false
        center_text = false
        clock_style = "digital"
        color = "primary"
        font_family = "IBM Plex Serif Light"
        format = """{:%A}
{:%-d %B}"""
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-name]
    box_height = 70.0
    box_width = 240.0
    cx = 1420.0
    cy = 770.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-name.settings]
        background = false
        color = "on_surface"
        description = ""
        font_family = "IBM Plex Sans Light"
        shadow = true
        title = "ayoub"

    [lockscreen_widgets.widget.lockscreen-widget-time]
    box_height = 240.0
    box_width = 640.0
    cx = 380.0
    cy = 770.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-time.settings]
        background = false
        center_text = false
        clock_style = "digital"
        color = "on_surface"
        font_family = "IBM Plex Sans Thin"
        format = "{:%H:%M}"
        shadow = true

[plugins]
enabled = [ "rxtsel/portctl", "yuuto/arch-updater" ]

[shell.greeter_sync]
auto_sync = true

[shell.panel]
control_center_placement = "floating"
open_near_click_control_center = true
transparency_mode = "soft"

[shell.session]
grid_columns = 4

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/ayoub/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/ayoub/Pictures/Wallpapers/anime-scenery-jeeq3q.png"

    [wallpaper.last]
    path = "/home/ayoub/Pictures/Wallpapers/anime-scenery-jeeq3q.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/ayoub/Pictures/Wallpapers/anime-scenery-jeeq3q.png"

[weather]
enabled = false

[widget.bluetooth]
enabled = false

[widget.brightness]
enabled = false

[widget.launcher]
glyph = "cube"

[widget.network]
enabled = false

[widget.notifications]
enabled = false

[widget.power_profile]
enabled = false

[widget.spacer_2]
type = "spacer"